@host = http://127.0.0.1:3000/api

###
# @name menus
GET {{host}}/menus/getMenus HTTp/1.1
Content-Type: application/json

###
# @name books
GET {{host}}/books/getBooks HTTp/1.1
Content-Type: application/json

###
# @name session
GET {{host}}/auth/signin HTTp/1.1
Content-Type: application/json

###
# @name session
GET {{host}}/matters/getMatters HTTp/1.1
Content-Type: application/json

###
# @name stopWatchItems
GET {{host}}/lawyer-stopwatch/getStopWatchItems HTTp/1.1
Content-Type: application/json

###
# @name stopWatchItems
POST {{host}}/lawyer-stopwatch/addStopwatchItems HTTp/1.1
Content-Type: application/json

[
  {
    "narration": "Fusce consequat. Nulla nisl.",
    "itemDate": "2022-12-02T07:30:37Z",
    "startedAt": "2023-04-20T22:14:54Z",
    "endedAt": null,
    "createdById": "cllds5v370000hbzg25sorxzj",
    "taskId": 11,
    "matterId": 1196
  },
  {
    "narration": "Fusce consequat. Nulla nisl.",
    "itemDate": "2022-12-02T07:30:37Z",
    "startedAt": "2023-04-20T22:14:54Z",
    "endedAt": null,
    "createdById": "cllds5v370000hbzg25sorxzj",
    "taskId": 11,
    "matterId": 1196
  }
]


###
# @name stopWatchItems
POST {{host}}/leave/post HTTp/1.1
Content-Type: application/json

{
    "employeeId": "clozjrltt002dhbj8ksb70bem",
    "supervisorId": "clozjrlu4002fhbj8vtuaaxlv",
    "leaveTypeId": "clozjrvtu0294hbj85ge7usxe",
    "duration": 76,
    "startDate": "1984-10-15T00:00:00.000Z",
    "endDate": "2014-08-03T00:00:00.000Z",
    "reportDate": "1971-06-21T00:00:00.000Z",
    "approvingHRMId": "clozjrlk6000rhbj8v8qtuki9",
    "approvingPartnerId": "clozjrm470047hbj8ebwjgedx"
  }


