export function getDesignations() {
	return [
		{ name: 'Accountant', staffTypeId: 2 },
		{ name: 'Associate', staffTypeId: 1 },
		{ name: 'Business Development Assistant', staffTypeId: 2 },
		{ name: 'Bill Reviewer', staffTypeId: 1 },
		{ name: 'Cleaner', staffTypeId: 2 },
		{ name: 'Clerk', staffTypeId: 2 },
		{ name: 'Deputy Head of Business Develoment', staffTypeId: 2 },
		{ name: 'Deputy Managing Partner', staffTypeId: 1 },
		{ name: 'Driver', staffTypeId: 2 },
		{ name: 'Founding Partner', staffTypeId: 1 },
		{ name: 'Head of Business Development', staffTypeId: 2 },
		{ name: 'Head of Finance', staffTypeId: 2 },
		{ name: 'Head of Human Resource', staffTypeId: 2 },
		{ name: 'Head of Information Technology', staffTypeId: 2 },
		{ name: 'IT Assistant', staffTypeId: 2 },
		{ name: 'Lawyer', staffTypeId: 1 },
		{ name: 'Librarian', staffTypeId: 2 },
		{ name: 'Marketing & BD Executive', staffTypeId: 2 },
		{ name: 'Managing Partner', staffTypeId: 1 },
		{ name: 'Partner', staffTypeId: 1 },
		{ name: 'Personal Assistant', staffTypeId: 2 },
		{ name: 'Pupil', staffTypeId: 1 },
		{ name: 'Register Clerk', staffTypeId: 2 },
		{ name: 'Senior Associate', staffTypeId: 1 },
		{ name: 'Senior Partner', staffTypeId: 1 },
		{ name: 'Systems Administrator', staffTypeId: 2 },
	];
}
