export function getMenus() {
	return [
		{
			name: 'Staff List',
			url: '/staff/staff-list/',
			icon: 'solar:users-group-two-rounded-outline',
			listOrder: 1,
		},
		{
			name: 'Lawyer Stopwatch',
			url: '/lawyer/lawyer-stopwatch/',
			icon: 'octicon:stopwatch-24',
			listOrder: 2,
		},
		{
			name: 'Bring-Ups',
			url: '/lawyer/bring-ups/',
			icon: 'basil:notification-on-outline',
			listOrder: 3,
		},
		{
			name: 'Projects',
			url: '/projects/',
			icon: 'teenyicons:gantt-chart-solid',
			listOrder: 4,
		},
		{
			name: 'Cause Lists',
			url: '/court/cause-lists/',
			icon: 'bi:file-text',
			listOrder: 5,
		},
		{
			name: 'Allocation Register',
			url: '/allocation-register/',
			icon: 'healthicons:register-book-outline',
			listOrder: 6,
		},
		{
			name: 'Minutes',
			url: '/meeting/minutes/',
			icon: 'tabler:file-text',
			listOrder: 7,
		},
		{
			name: 'Memos',
			url: '/meeting/memos/',
			icon: 'radix-icons:file-text',
			listOrder: 8,
		},
		{
			name: 'Official Letters',
			url: '/meeting/official-letters/',
			icon: 'solar:letter-opened-outline',
			listOrder: 9,
		},
		{
			name: 'KYC Checklist',
			url: '/kyc-checklists/',
			icon: 'fluent:clipboard-task-list-ltr-24-regular',
			listOrder: 10,
		},
		{
			name: 'Leave Application',
			url: '/staff/leave-applications/',
			icon: 'material-symbols:perm-contact-calendar-outline',
			listOrder: 11,
		},
		{
			name: 'Matter Submission',
			url: '/matter-submissions/',
			icon: 'iconoir:submit-document',
			listOrder: 12,
		},
		{
			name: 'Court Attendance Notes',
			url: '/court/court-attendances/',
			icon: 'pixelarticons:notes-multiple',
			listOrder: 13,
		},
		{
			name: 'Instruction Notes',
			url: '/court/instruction-notes/',
			icon: 'gg:notes',
			listOrder: 14,
		},
		{
			name: 'Deposit Request Notes',
			url: '/finance/deposit-request-notes/',
			icon: 'iconamoon:invoice-light',
			listOrder: 15,
		},
		{
			name: 'Fee Notes',
			url: '/finance/fee-notes/',
			icon: 'teenyicons:invoice-outline',
			listOrder: 16,
		},
		{
			name: 'Credit Notes',
			url: '/finance/credit-notes/',
			icon: 'basil:invoice-outline',
			listOrder: 17,
		},
		{
			name: 'Purchase Orders',
			url: '/finance/purchase-orders/',
			icon: 'nimbus:invoice',
			listOrder: 18,
		},
		{
			name: 'Employee Recruitment',
			url: '/staff/recruitments/',
			icon: 'clarity:employee-line',
			listOrder: 19,
		},
		{
			name: 'Staff Particulars',
			url: '/staff/staff-particulars/',
			icon: 'mdi:account-tie-outline',
			listOrder: 20,
		},
		{
			name: 'Exit Checklist',
			url: '/staff/exit-checklists/',
			icon: 'ic:round-list-alt',
			listOrder: 21,
		},
		{
			name: 'Library',
			url: '/library/',
			icon: 'fluent:library-24-regular',
			listOrder: 22,
		},
		{
			name: 'Newsfeed',
			url: '/newsfeed/',
			icon: 'emojione-monotone:newspaper',
			listOrder: 23,
		},
		{
			name: 'Events',
			url: '/events/',
			icon: 'heroicons:calendar-days-solid',
			listOrder: 24,
		},
		{
			name: 'Asset Management',
			url: '/asset-management/',
			icon: 'material-symbols:inventory-2-outline',
			listOrder: 25,
		},
	];
}
