export function getSubMenus() {
	return [
		{
			menu_id: 1,
			name: 'Lawyer Stopwatch',
			url: '/lawyer/lawyer-stopwatch/',
			icon: 'octicon:stopwatch-24',
			list_order: 1,
		},
		{
			menu_id: 1,
			name: 'Bring-Ups',
			url: '/lawyer/bring-ups/',
			icon: 'basil:notification-on-outline',
			list_order: 2,
		},
		{
			menu_id: 2,
			name: 'Court Attendance Notes',
			url: '/court/court-attendances/',
			icon: 'pixelarticons:notes-multiple',
			list_order: 1,
		},
		{
			menu_id: 2,
			name: 'Instruction Notes',
			url: '/court/instruction-notes/',
			icon: 'gg:notes',
			list_order: 2,
		},
		{
			menu_id: 2,
			name: 'Cause Lists',
			url: '/court/cause-lists/',
			icon: 'bi:file-text',
			list_order: 3,
		},
		{
			menu_id: 3,
			name: 'Minutes',
			url: '/meeting/minutes/',
			icon: 'tabler:file-text',
			list_order: 1,
		},
		{
			menu_id: 3,
			name: 'Memos',
			url: '/meeting/memos/',
			icon: 'radix-icons:file-text',
			list_order: 2,
		},
		{
			menu_id: 3,
			name: 'Official Letters',
			url: '/meeting/official-letters/',
			icon: 'solar:letter-opened-outline',
			list_order: 3,
		},
		{
			menu_id: 4,
			name: 'Deposit Request Notes',
			url: '/finance/deposit-request-notes/',
			icon: 'iconamoon:invoice-light',
			list_order: 1,
		},
		{
			menu_id: 4,
			name: 'Fee Notes',
			url: '/finance/fee-notes/',
			icon: 'teenyicons:invoice-outline',
			list_order: 2,
		},
		{
			menu_id: 4,
			name: 'Credit Notes',
			url: '/finance/credit-notes/',
			icon: 'basil:invoice-outline',
			list_order: 3,
		},
		{
			menu_id: 4,
			name: 'Purchase Orders',
			url: '/finance/purchase-orders/',
			icon: 'nimbus:invoice',
			list_order: 4,
		},
		{
			menu_id: 9,
			name: 'Staff List',
			url: '/staff/staff-list/',
			icon: 'solar:users-group-two-rounded-outline',
			list_order: 1,
		},
		{
			menu_id: 9,
			name: 'Leave Application',
			url: '/staff/leave-applications/',
			icon: 'material-symbols:perm-contact-calendar-outline',
			list_order: 1,
		},
		{
			menu_id: 9,
			name: 'Employee Recruitment',
			url: '/staff/recruitments/',
			icon: 'clarity:employee-line',
			list_order: 2,
		},
		{
			menu_id: 9,
			name: 'Staff Particulars',
			url: '/staff/staff-particulars/',
			icon: 'mdi:account-tie-outline',
			list_order: 3,
		},
		{
			menu_id: 9,
			name: 'Exit Checklist',
			url: '/staff/exit-checklists/',
			icon: 'ic:round-list-alt',
			list_order: 4,
		},
	];
}
