-- AlterTable
ALTER TABLE "Book" ALTER COLUMN "updatedAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Staff" ALTER COLUMN "updatedAt" DROP NOT NULL;
